name = 'gutter-cleaners-uxbridge'
main="worker/index.js"
compatibility_date = "2026-05-05"
compatibility_flags = [ "nodejs_compat" ]
preview_urls = true

[observability.logs]
enabled = false

[placement]
mode = "smart"

[assets]
directory = "./dist"
not_found_handling = "404-page"
html_handling = "force-trailing-slash"
run_worker_first = ["/~*"]

[[d1_databases]]
binding = "DB"
database_name = "gcu-leads"
database_id = "41cb394c-1cdb-43e8-b59d-6e97450878c9"

[[routes]]
pattern = "guttercleanersuxbridge.co.uk"
custom_domain = true

[[routes]]
pattern = "www.guttercleanersuxbridge.co.uk"
custom_domain = true
